### PR TITLE
Return foreman, allowing later manipulation of the child process.

### PR DESCRIPTION
**Pull request by ghost**
I added a one-line change to return the foreman child process, so that one can make other calls to the child process later, such as kill() to stop a server process.

### CODE REVIEW

**Comment by jshcrowthe** [comment]
@maldrake Again I like the change. If you will add the same things I requested in #4 we'll go ahead and merge this in.

**Comment by ghost** [comment]
I added the demo and incremented the package version number, similar to #4.  Thank you for your consideration of both PRs.

**Comment by jshcrowthe** [comment]
@maldrake: I apologize for the delay, I have tested and we are good to go!

**Comment by ghost** [comment]
Great -- thank you!

**Pull request merged**
